### ISSUE TITLE
> THE README IS NOT BESPOKE ENOUGH MAKE IT MORE

### ISSUE THREAD

**Issue by vivekkushalch** [Imon-stack/Imon-stack#2]
> THE README IS NOT BESPOKE ENOUGH MAKE IT MORE

IT IS ENOUGH TO MAKE YOU FALL FROM THE CHAIR

_Originally posted by @Jeet-programmer in https://github.com/Imon-stack/Imon-stack/issues/1#issuecomment-1545982113_

**Comment by vivekkushalch** [comment]
HUHHHHHH THIS DOSENT MAKE SENSE ITS NOT MY CHAIR ITS HIS

**Comment by Imon-stack** [comment]
HUMBA HUMBA BUMBA BUMBA
